const users = [
  {
    id: "410544b2-4001-4271-9855-fec4b6a6442a",
    name: "User",
    email: "user@carhive.com",
    password: "123456",
  },
]

const testimonials = [
  {
    id: "985425fe-0c7e-4700-8e6d-d48b3bc66768",
    name: "Olivia Parker",
    comment:
      "Best Car Rental Experience! The website's interface is intuitive, making it easy to find the ideal car. The reviews from other users were incredibly helpful, and the entire process, from booking to return, was a breeze. Highly recommended!",
    username: "oliviaparker",
    image_url: "avatars/olivia-parker_aembie",
  },
  {
    id: "6671f37d-75ad-404f-bf23-04ddff964aa5",
    name: "Emma Thompson",
    comment:
      "A Seamless Experience! This website made renting a car hassle-free. The search filters helped me find the perfect car for my trip, and the customer support was responsive and friendly. 5-star service all the way!",
    username: "emmathompson",
    image_url: "avatars/emma-thompson_o2ivnb",
  },
  {
    id: "8ecd373f-65c7-4651-a575-63325489297a",
    name: "Sophia Rodriguez",
    comment:
      "Reliable and Affordable! I've used several car rental websites before, but this one stands out. The prices are transparent, no hidden fees, and the cars are well-maintained. I'll be coming back for all my future trips.",
    username: "sophiarodriguez",
    image_url: "avatars/sophia-rodriguez_rxxvrc",
  },
  {
    id: "944fdb07-590d-4cb1-a797-e7fb672c84e1",
    name: "Daniel Johnson",
    comment:
      "Exceptional Service! From booking to drop-off, everything was smooth and easy. The selection of cars was impressive, and the prices were unbeatable. Will definitely recommend to friends!",
    username: "danjohnson",
    image_url: "avatars/daniel-johnson_vnlm3m",
  },
]

const cars = [
  {
    id: "6cdd6d3e-49f2-4c70-897b-81f3e3cb0c6a",
    slug: "hybrid-hatchback-basic",
    name: "Hatchback Basic",
    body_style: "hatchback",
    powertrain: "hybrid",
    transmission: "automatic",
    seats: 5,
    description:
      "A basic hybrid hatchback that offers efficiency and practicality for daily use, featuring modern technology and a comfortable ride for urban commuting.",
    features: [
      "Bluetooth Connectivity",
      "Rearview Camera",
      "Navigation System",
      "Keyless Entry",
    ],
    rating: 4.5,
    review_count: 150,
    unlimited_mileage: true,
    image_url: "carhive/cars/hatchback_hawhtv",
    price_per_day: 45.99,
    currency: "USD",
  },
  {
    id: "d462a8b7-0e94-4ec9-8d57-d3e1db88b1d5",
    slug: "gasoline-sedan-luxury",
    name: "Sedan Luxury",
    body_style: "sedan",
    powertrain: "gasoline",
    transmission: "automatic",
    seats: 5,
    description:
      "A luxury gasoline sedan providing a sophisticated driving experience with premium features and a smooth ride for both city and highway travel.",
    features: [
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
      "Rearview Camera",
      "Adaptive Cruise Control",
    ],
    rating: 4.8,
    review_count: 200,
    unlimited_mileage: true,
    image_url: "carhive/cars/sedan_rfl011",
    price_per_day: 85.0,
    currency: "USD",
  },
  {
    id: "e88bbffb-fd2d-42c1-85ff-b37d46d9512d",
    slug: "electric-sports-car-fast",
    name: "Sports Car Fast",
    body_style: "sports-car",
    powertrain: "electric",
    transmission: "automatic",
    seats: 2,
    description:
      "An electric sports car designed for speed and performance, featuring advanced technology and a sleek design for an exhilarating driving experience.",
    features: [
      "Sport Mode",
      "Bluetooth Connectivity",
      "Navigation System",
      "Leather Seats",
      "Rearview Camera",
    ],
    rating: 4.9,
    review_count: 250,
    unlimited_mileage: true,
    image_url: "carhive/cars/sports-car_hmxtaj",
    price_per_day: 110.0,
    currency: "USD",
  },
  {
    id: "f11a1c1d-b8ee-44b6-926c-fcf7f715e5d2",
    slug: "diesel-pickup-truck-rugged",
    name: "Pickup Truck Rugged",
    body_style: "pickup-truck",
    powertrain: "diesel",
    transmission: "manual",
    seats: 5,
    description:
      "A rugged diesel pickup truck designed for tough jobs and off-road adventures, offering high durability and powerful performance for demanding tasks.",
    features: [
      "Tow Package",
      "Bluetooth Connectivity",
      "Navigation System",
      "Backup Camera",
      "All-Terrain Tires",
    ],
    rating: 4.6,
    review_count: 180,
    unlimited_mileage: true,
    image_url: "carhive/cars/pickup-truck_ihwn41",
    price_per_day: 65.0,
    currency: "USD",
  },
  {
    id: "9b9e8e76-5274-40b8-b8a3-6bfe2a790df7",
    slug: "hybrid-minivan-family",
    name: "Minivan Family",
    body_style: "minivan",
    powertrain: "hybrid",
    transmission: "automatic",
    seats: 8,
    description:
      "A family-friendly hybrid minivan offering plenty of space and advanced features for a comfortable and eco-friendly travel experience.",
    features: [
      "Rear Sliding Doors",
      "Navigation System",
      "Bluetooth Connectivity",
      "Apple CarPlay",
      "Power Tailgate",
    ],
    rating: 4.7,
    review_count: 190,
    unlimited_mileage: true,
    image_url: "carhive/cars/minivan_vlkx4g",
    price_per_day: 80.0,
    currency: "USD",
  },
  {
    id: "7b6f5a2c-6d14-4938-a545-8e4cb57e2d74",
    slug: "electric-hatchback-compact",
    name: "Hatchback Compact",
    body_style: "hatchback",
    powertrain: "electric",
    transmission: "automatic",
    seats: 4,
    description:
      "A compact electric hatchback perfect for city driving, combining energy efficiency with modern features and a stylish design for urban commuters.",
    features: [
      "Navigation System",
      "Bluetooth Connectivity",
      "Rearview Camera",
      "Apple CarPlay",
      "Keyless Entry",
    ],
    rating: 4.4,
    review_count: 170,
    unlimited_mileage: true,
    image_url: "carhive/cars/hatchback_hawhtv",
    price_per_day: 55.0,
    currency: "USD",
  },
  {
    id: "6c3c8c8f-87b1-4cc2-b6f2-9b15d5b17e05",
    slug: "gasoline-suv-comfort",
    name: "SUV Comfort",
    body_style: "suv",
    powertrain: "gasoline",
    transmission: "automatic",
    seats: 7,
    description:
      "A comfortable gasoline SUV designed for family trips and daily driving, featuring a spacious interior and modern amenities for a pleasant ride.",
    features: [
      "Navigation System",
      "Bluetooth Connectivity",
      "Heated Seats",
      "Rearview Camera",
      "Apple CarPlay",
      "Adaptive Cruise Control",
    ],
    rating: 4.7,
    review_count: 160,
    unlimited_mileage: true,
    image_url: "carhive/cars/suv_rdgyby",
    price_per_day: 75.0,
    currency: "USD",
  },
  {
    id: "4c3b3b42-682b-4d46-9fd3-c40d99a0535d",
    slug: "diesel-sedan-economy",
    name: "Sedan Economy",
    body_style: "sedan",
    powertrain: "diesel",
    transmission: "manual",
    seats: 5,
    description:
      "An economical diesel sedan offering great fuel efficiency and a comfortable ride, ideal for budget-conscious drivers seeking reliability and performance.",
    features: [
      "Bluetooth Connectivity",
      "Navigation System",
      "Rearview Camera",
      "Keyless Entry",
      "Apple CarPlay",
    ],
    rating: 4.5,
    review_count: 175,
    unlimited_mileage: true,
    image_url: "carhive/cars/sedan_rfl011",
    price_per_day: 60.0,
    currency: "USD",
  },
  {
    id: "2d8d3a48-0a1e-4d9b-92f3-0a7b785b8f6b",
    slug: "electric-pickup-truck-flex",
    name: "Pickup Truck Flex",
    body_style: "pickup-truck",
    powertrain: "electric",
    transmission: "automatic",
    seats: 5,
    description:
      "A versatile electric pickup truck designed for both work and leisure, offering impressive range and durability with a rugged design.",
    features: [
      "Tow Package",
      "Bluetooth Connectivity",
      "Navigation System",
      "Backup Camera",
      "All-Terrain Tires",
    ],
    rating: 4.6,
    review_count: 190,
    unlimited_mileage: true,
    image_url: "carhive/cars/pickup-truck_ihwn41",
    price_per_day: 85.0,
    currency: "USD",
  },
  {
    id: "e41c60e5-2212-42ea-9753-bd8f1e60d1da",
    slug: "hybrid-suv-adventure",
    name: "SUV Adventure",
    body_style: "suv",
    powertrain: "hybrid",
    transmission: "automatic",
    seats: 5,
    description:
      "An adventure-ready hybrid SUV designed for both urban and off-road experiences, offering a blend of efficiency, power, and modern features.",
    features: [
      "Navigation System",
      "Bluetooth Connectivity",
      "Rearview Camera",
      "Apple CarPlay",
      "All-Terrain Tires",
    ],
    rating: 4.8,
    review_count: 210,
    unlimited_mileage: true,
    image_url: "carhive/cars/suv_rdgyby",
    price_per_day: 78.0,
    currency: "USD",
  },
  {
    id: "d773d903-54b3-4a36-9b74-0e6d2f87761f",
    slug: "gasoline-hatchback-sporty",
    name: "Hatchback Sporty",
    body_style: "hatchback",
    powertrain: "gasoline",
    transmission: "manual",
    seats: 4,
    description:
      "A sporty gasoline hatchback designed for performance and agility, featuring a dynamic driving experience with advanced features for enthusiasts.",
    features: [
      "Sport Mode",
      "Bluetooth Connectivity",
      "Navigation System",
      "Rearview Camera",
      "Leather Seats",
    ],
    rating: 4.6,
    review_count: 165,
    unlimited_mileage: true,
    image_url: "carhive/cars/hatchback_hawhtv",
    price_per_day: 62.0,
    currency: "USD",
  },
  {
    id: "5735b7c2-8e9b-4f7f-855e-49f21a715c92",
    slug: "electric-sedan-premium",
    name: "Sedan Premium",
    body_style: "sedan",
    powertrain: "electric",
    transmission: "automatic",
    seats: 5,
    description:
      "A premium electric sedan offering luxury and advanced technology, combining a smooth ride with zero emissions and high-end features for an exceptional driving experience.",
    features: [
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
      "Adaptive Cruise Control",
      "Rearview Camera",
      "Apple CarPlay",
    ],
    rating: 4.9,
    review_count: 220,
    unlimited_mileage: true,
    image_url: "carhive/cars/sedan_rfl011",
    price_per_day: 95.0,
    currency: "USD",
  },
  {
    id: "a93f0b2b-4f02-4b5d-b0cc-234eaaecfbfd",
    slug: "hybrid-sports-car-elite",
    name: "Sports Car Elite",
    body_style: "sports-car",
    powertrain: "hybrid",
    transmission: "automatic",
    seats: 2,
    description:
      "An elite hybrid sports car offering high performance and eco-friendly technology, featuring a sleek design and advanced features for a thrilling driving experience.",
    features: [
      "Sport Mode",
      "Navigation System",
      "Bluetooth Connectivity",
      "Leather Seats",
      "Rearview Camera",
    ],
    rating: 4.8,
    review_count: 200,
    unlimited_mileage: true,
    image_url: "carhive/cars/sports-car_hmxtaj",
    price_per_day: 120.0,
    currency: "USD",
  },
  {
    id: "7a5e4e51-1e29-487c-9a09-d8a1e7b9796e",
    slug: "gasoline-minivan-spacious",
    name: "Minivan Spacious",
    body_style: "minivan",
    powertrain: "gasoline",
    transmission: "automatic",
    seats: 8,
    description:
      "A spacious gasoline minivan perfect for large families, offering ample room, comfort, and modern features for enjoyable long drives and everyday use.",
    features: [
      "Rear Sliding Doors",
      "Navigation System",
      "Bluetooth Connectivity",
      "Power Tailgate",
      "Apple CarPlay",
      "Heated Seats",
    ],
    rating: 4.6,
    review_count: 170,
    unlimited_mileage: true,
    image_url: "carhive/cars/minivan_vlkx4g",
    price_per_day: 75.0,
    currency: "USD",
  },
  {
    id: "04df75a5-d495-4192-927d-4c54e68feca9",
    slug: "electric-hatchback-sleek",
    name: "Hatchback Sleek",
    body_style: "hatchback",
    powertrain: "electric",
    transmission: "automatic",
    seats: 4,
    description:
      "A sleek electric hatchback with a modern design and advanced technology, offering a stylish and efficient driving experience with a focus on sustainability.",
    features: [
      "Navigation System",
      "Bluetooth Connectivity",
      "Rearview Camera",
      "Apple CarPlay",
      "Keyless Entry",
    ],
    rating: 4.7,
    review_count: 180,
    unlimited_mileage: true,
    image_url: "carhive/cars/hatchback_hawhtv",
    price_per_day: 60.0,
    currency: "USD",
  },
  {
    id: "e2c6c9c2-8a5d-4f77-b431-3f86d0454c1b",
    slug: "diesel-sports-car-racing",
    name: "Sports Car Racing",
    body_style: "sports-car",
    powertrain: "diesel",
    transmission: "manual",
    seats: 2,
    description:
      "A high-performance diesel sports car engineered for racing and driving enthusiasts, featuring a powerful engine and advanced handling capabilities for thrilling drives.",
    features: [
      "Sport Mode",
      "Navigation System",
      "Bluetooth Connectivity",
      "Leather Seats",
      "Rearview Camera",
    ],
    rating: 4.9,
    review_count: 210,
    unlimited_mileage: true,
    image_url: "carhive/cars/sports-car_hmxtaj",
    price_per_day: 130.0,
    currency: "USD",
  },
  {
    id: "d30b28a1-e9d7-43ed-9cbf-dfd4bda0c24f",
    slug: "hybrid-sedan-standard",
    name: "Sedan Standard",
    body_style: "sedan",
    powertrain: "hybrid",
    transmission: "automatic",
    seats: 5,
    description:
      "A standard hybrid sedan offering a balanced combination of efficiency and comfort, equipped with modern features and designed for everyday driving.",
    features: [
      "Navigation System",
      "Bluetooth Connectivity",
      "Rearview Camera",
      "Apple CarPlay",
      "Keyless Entry",
    ],
    rating: 4.5,
    review_count: 160,
    unlimited_mileage: true,
    image_url: "carhive/cars/sedan_rfl011",
    price_per_day: 68.0,
    currency: "USD",
  },
  {
    id: "b8fbc55c-8a8a-4f92-9b55-cb56edc28dc8",
    slug: "gasoline-pickup-truck-work",
    name: "Pickup Truck Work",
    body_style: "pickup-truck",
    powertrain: "gasoline",
    transmission: "manual",
    seats: 5,
    description:
      "A reliable gasoline pickup truck designed for work and utility, featuring a robust build and essential features for handling heavy-duty tasks and transporting goods.",
    features: [
      "Tow Package",
      "Bluetooth Connectivity",
      "Navigation System",
      "Backup Camera",
      "All-Terrain Tires",
    ],
    rating: 4.4,
    review_count: 140,
    unlimited_mileage: true,
    image_url: "carhive/cars/pickup-truck_ihwn41",
    price_per_day: 70.0,
    currency: "USD",
  },
  {
    id: "9b7d8e58-3c1a-4a9d-a74f-ff40e835e8c7",
    slug: "electric-sports-car-elite",
    name: "Sports Car Elite",
    body_style: "sports-car",
    powertrain: "electric",
    transmission: "automatic",
    seats: 2,
    description:
      "An elite electric sports car offering unparalleled performance and cutting-edge technology, featuring a sleek design and high-end features for an extraordinary driving experience.",
    features: [
      "Sport Mode",
      "Navigation System",
      "Bluetooth Connectivity",
      "Leather Seats",
      "Rearview Camera",
      "Apple CarPlay",
    ],
    rating: 4.9,
    review_count: 200,
    unlimited_mileage: true,
    image_url: "carhive/cars/sports-car_hmxtaj",
    price_per_day: 140.0,
    currency: "USD",
  },
  {
    id: "65df8e76-3e40-4899-a91d-0e50a7eb2352",
    slug: "gasoline-suv-adventure",
    name: "SUV Adventure",
    body_style: "suv",
    powertrain: "gasoline",
    transmission: "automatic",
    seats: 7,
    description:
      "A versatile gasoline SUV designed for adventure, combining spaciousness, power, and advanced features for an enjoyable driving experience both on and off the road.",
    features: [
      "Navigation System",
      "Bluetooth Connectivity",
      "All-Terrain Tires",
      "Rearview Camera",
      "Apple CarPlay",
    ],
    rating: 4.7,
    review_count: 190,
    unlimited_mileage: true,
    image_url: "carhive/cars/suv_rdgyby",
    price_per_day: 80.0,
    currency: "USD",
  },
  {
    id: "efcb3a11-5b38-4d70-92f4-25f3485a7e2b",
    slug: "hybrid-pickup-truck-utility",
    name: "Pickup Truck Utility",
    body_style: "pickup-truck",
    powertrain: "hybrid",
    transmission: "automatic",
    seats: 5,
    description:
      "A hybrid pickup truck designed for utility and efficiency, featuring a powerful hybrid engine and essential features for handling work tasks and daily drives.",
    features: [
      "Tow Package",
      "Bluetooth Connectivity",
      "Navigation System",
      "Backup Camera",
      "All-Terrain Tires",
    ],
    rating: 4.6,
    review_count: 150,
    unlimited_mileage: true,
    image_url: "carhive/cars/pickup-truck_ihwn41",
    price_per_day: 85.0,
    currency: "USD",
  },
  {
    id: "d08d8b44-22f5-4b8c-a3d2-84e4d084fb95",
    slug: "gasoline-sedan-comfort",
    name: "Sedan Comfort",
    body_style: "sedan",
    powertrain: "gasoline",
    transmission: "automatic",
    seats: 5,
    description:
      "A comfortable gasoline sedan designed for daily commutes and long drives, offering a smooth ride and a range of modern features for a relaxing driving experience.",
    features: [
      "Navigation System",
      "Bluetooth Connectivity",
      "Rearview Camera",
      "Apple CarPlay",
      "Heated Seats",
    ],
    rating: 4.6,
    review_count: 175,
    unlimited_mileage: true,
    image_url: "carhive/cars/sedan_rfl011",
    price_per_day: 65.0,
    currency: "USD",
  },
  {
    id: "8f2e8a2e-5b40-44ab-817f-42d4b1e8e45e",
    slug: "electric-minivan-premium",
    name: "Minivan Premium",
    body_style: "minivan",
    powertrain: "electric",
    transmission: "automatic",
    seats: 7,
    description:
      "A premium electric minivan combining spaciousness with cutting-edge technology, offering a quiet and efficient driving experience with top-tier features for families.",
    features: [
      "Navigation System",
      "Bluetooth Connectivity",
      "Rearview Camera",
      "Apple CarPlay",
      "Power Sliding Doors",
      "Heated Seats",
    ],
    rating: 4.8,
    review_count: 185,
    unlimited_mileage: true,
    image_url: "carhive/cars/minivan_vlkx4g",
    price_per_day: 88.0,
    currency: "USD",
  },
  {
    id: "21b15b2b-9ef2-4f18-855c-31e4b68c935e",
    slug: "diesel-suv-heavy-duty",
    name: "SUV Heavy Duty",
    body_style: "suv",
    powertrain: "diesel",
    transmission: "automatic",
    seats: 7,
    description:
      "A heavy-duty diesel SUV built for rugged terrain and tough tasks, featuring powerful performance and advanced off-road capabilities for challenging drives.",
    features: [
      "Navigation System",
      "Bluetooth Connectivity",
      "All-Terrain Tires",
      "Rearview Camera",
      "Tow Package",
    ],
    rating: 4.7,
    review_count: 190,
    unlimited_mileage: true,
    image_url: "carhive/cars/suv_rdgyby",
    price_per_day: 85.0,
    currency: "USD",
  },
  {
    id: "6035ae38-565f-4c68-bbfa-851e7f5a96d6",
    slug: "hybrid-suv-family",
    name: "SUV Family",
    body_style: "suv",
    powertrain: "hybrid",
    transmission: "automatic",
    seats: 7,
    description:
      "A family-friendly hybrid SUV with spacious seating and eco-friendly technology, combining comfort, efficiency, and modern features for family adventures.",
    features: [
      "Navigation System",
      "Bluetooth Connectivity",
      "Rearview Camera",
      "Apple CarPlay",
      "Heated Seats",
    ],
    rating: 4.6,
    review_count: 165,
    unlimited_mileage: true,
    image_url: "carhive/cars/suv_rdgyby",
    price_per_day: 78.0,
    currency: "USD",
  },
  {
    id: "cbcd72c1-4cb4-4bb0-b9e1-28b9fc7e6209",
    slug: "gasoline-sports-car-compact",
    name: "Sports Car Compact",
    body_style: "sports-car",
    powertrain: "gasoline",
    transmission: "manual",
    seats: 2,
    description:
      "A compact gasoline sports car designed for agility and speed, featuring a sleek design and advanced features for a thrilling and dynamic driving experience.",
    features: [
      "Sport Mode",
      "Bluetooth Connectivity",
      "Navigation System",
      "Leather Seats",
      "Rearview Camera",
    ],
    rating: 4.5,
    review_count: 155,
    unlimited_mileage: true,
    image_url: "carhive/cars/sports-car_hmxtaj",
    price_per_day: 110.0,
    currency: "USD",
  },
  {
    id: "2ae2b03e-1c8e-4a9e-a1c4-85e452a16b38",
    slug: "electric-sedan-luxury",
    name: "Sedan Luxury",
    body_style: "sedan",
    powertrain: "electric",
    transmission: "automatic",
    seats: 5,
    description:
      "A luxury electric sedan offering top-notch performance and advanced technology, providing a refined and eco-friendly driving experience with exceptional comfort and features.",
    features: [
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
      "Adaptive Cruise Control",
      "Rearview Camera",
      "Apple CarPlay",
    ],
    rating: 4.9,
    review_count: 210,
    unlimited_mileage: true,
    image_url: "carhive/cars/sedan_rfl011",
    price_per_day: 100.0,
    currency: "USD",
  },
  {
    id: "7bfbfd42-3d87-49eb-82fc-4a1edc711a06",
    slug: "diesel-pickup-truck-heavy-duty",
    name: "Pickup Truck Heavy Duty",
    body_style: "pickup-truck",
    powertrain: "diesel",
    transmission: "manual",
    seats: 5,
    description:
      "A heavy-duty diesel pickup truck designed for tough jobs and rugged terrain, offering exceptional power and durability for demanding tasks and off-road adventures.",
    features: [
      "Tow Package",
      "Bluetooth Connectivity",
      "Navigation System",
      "Backup Camera",
      "All-Terrain Tires",
    ],
    rating: 4.8,
    review_count: 190,
    unlimited_mileage: true,
    image_url: "carhive/cars/pickup-truck_ihwn41",
    price_per_day: 95.0,
    currency: "USD",
  },
]

const locations = [
  {
    id: "fae436f3-6341-486a-8691-0633f64e1997",
    name: "Amsterdam, Netherlands",
    slug: "amsterdam",
    latitude: 52.3547,
    longitude: 4.904,
    featured: false,
    image_url: "",
  },
  {
    id: "6132dc81-cc1a-4a2e-93c3-d176139bec4f",
    name: "Barcelona, Spain",
    slug: "barcelona",
    latitude: 41.3925,
    longitude: 2.1404,
    featured: false,
    image_url: "",
  },
  {
    id: "92331cbf-254a-4acf-9671-a77810faef4c",
    name: "Cancún, México",
    slug: "cancun",
    latitude: 21.1617,
    longitude: -86.851,
    featured: true,
    image_url: "locations/cancun_c1tw5i",
  },
  {
    id: "e27e9e7c-5bf9-44f9-b24f-3b5df6417c77",
    name: "Dubai, United Arab Emirates",
    slug: "dubai",
    latitude: 25.2652,
    longitude: 55.2928,
    featured: true,
    image_url: "locations/dubai_joqiup",
  },
  {
    id: "fd1e4b0d-5e1a-41db-a89b-6e33eed72ace",
    name: "New York, United States",
    slug: "new-york",
    latitude: 40.6975,
    longitude: -73.9795,
    featured: false,
    image_url: "",
  },
  {
    id: "45d07433-25e2-4ce7-b039-f0317e694048",
    name: "Paris, France",
    slug: "paris",
    latitude: 48.8589,
    longitude: 2.3469,
    featured: true,
    image_url: "locations/paris_tfbyw0",
  },
  {
    id: "d9b23370-3be4-4936-ae23-3ad54b310fd8",
    name: "Rio de Janeiro, Brazil",
    slug: "rio",
    latitude: -22.9148,
    longitude: -43.4075,
    featured: false,
    image_url: "",
  },
  {
    id: "2538dcf8-b531-4c68-a87a-b49a42be0c23",
    name: "Rome, Italy",
    slug: "rome",
    latitude: 41.8931,
    longitude: 12.4832,
    featured: true,
    image_url: "locations/rome_g8hdhk",
  },
  {
    id: "b31d9e0c-77c6-427b-9a19-37382ea62d7b",
    name: "Sydney, Australia",
    slug: "sydney",
    latitude: -33.8693,
    longitude: 151.209,
    featured: false,
    image_url: "",
  },
  {
    id: "ff841d10-0682-4e51-9330-47c5abb00643",
    name: "Tokyo, Japan",
    slug: "tokyo",
    latitude: 35.6841,
    longitude: 139.7742,
    featured: false,
    image_url: "",
  },
]

const rentalReservations = [
  {
    id: "a5288c3d-e859-4ecf-8f72-1840c02d6cff",
    car_id: cars[6].id,
    user_id: users[0].id,
    location_id: locations[1].id,
    check_in: "2024-03-10",
    check_out: "2024-03-18",
    created_at: "2023-10-28",
  },
]

const newsletterSubscribers = [
  {
    id: "8cdd2d76-0989-4711-9377-9fa9f5d15b6d",
    email: "test@carhive.com",
    created_at: "2023-10-31",
  },
]

module.exports = {
  users,
  testimonials,
  cars,
  rentalReservations,
  locations,
  newsletterSubscribers,
}
