import type { Metadata } from 'next';

import { SiteHeader } from '@/components/site-header';
import { MainSearchForm } from '@/components/main-search-form';
import { SiteFooter } from '@/components/site-footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface CarsLayoutProps {
  children: React.ReactNode;
}

export default function CarsLayout({ children }: CarsLayoutProps) {
  return (
    <>
      <div className="sticky top-0 z-20 h-[calc(var(--header-height)+var(--search-height))] w-full border-b border-black/10 bg-white">
        <div className="border-b">
          <div className="mx-auto h-[var(--header-height)] w-full max-w-none px-5 sm:max-w-none sm:px-6">
            <SiteHeader />
          </div>
        </div>
        <section className="h-[var(--search-height)]">
          <div className="hidden h-full items-center justify-center lg:flex">
            <MainSearchForm compact />
          </div>
        </section>
      </div>
      {children}
      <SiteFooter />
    </>
  );
}
