export const vehicles = [
  {
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "#",
    colors: ["red"],
    featured: true,
    details: {
      transmission: "automatic",
      seats: "5 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "#",
    colors: ["red"],
    featured: true,
    details: {
      transmission: "automatic",
      seats: "5 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "#",
    colors: ["red"],
    featured: true,
    details: {
      transmission: "automatic",
      seats: "5 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "#",
    colors: ["red"],
    featured: true,
    details: {
      transmission: "automatic",
      seats: "5 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "#",
    colors: ["red"],
    featured: false,
    details: {
      transmission: "automatic",
      seats: "5 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "#",
    colors: ["red"],
    featured: false,
    details: {
      transmission: "automatic",
      seats: "5 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "#",
    colors: ["red"],
    featured: false,
    details: {
      transmission: "automatic",
      seats: "5 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "#",
    colors: ["red"],
    featured: false,
    details: {
      transmission: "automatic",
      seats: "5 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "#",
    colors: ["red"],
    featured: false,
    details: {
      transmission: "automatic",
      seats: "5 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "#",
    colors: ["red"],
    featured: false,
    details: {
      transmission: "automatic",
      seats: "5 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "#",
    colors: ["red"],
    featured: false,
    details: {
      transmission: "automatic",
      seats: "5 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "#",
    colors: ["red"],
    featured: false,
    details: {
      transmission: "automatic",
      seats: "5 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
];
