export const vehicles = [
  {
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    year: 2019,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "tesla.jpg",
    color: { short: "white", long: "pearl white" },
    featured: true,
    details: {
      transmission: "automatic",
      seats: "4 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "mercedes-benz-cls",
    brand: "Porsche",
    model: "CLS",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "porsche.jpg",
    color: { short: "white", long: "pearl white" },
    featured: true,
    details: {
      transmission: "automatic",
      seats: "4 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "bmw-blue",
    brand: "BMW",
    model: "Lorem ipsum",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "bmw-blue.jpg",
    color: { short: "blue", long: "metallic blue" },
    featured: true,
    details: {
      transmission: "automatic",
      seats: "4 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "bmw-black",
    brand: "BMW",
    model: "Lorem ipsum",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "bmw-black.jpg",
    color: { short: "black", long: "black" },
    featured: false,
    details: {
      transmission: "automatic",
      seats: "4 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "van",
    brand: "Volkswagen",
    model: "Lorem ipsum",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "van.jpg",
    color: { short: "yellow", long: "yellow" },
    featured: true,
    details: {
      transmission: "automatic",
      seats: "8 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "hyundai-i30n",
    brand: "Hyundai",
    model: "I30N",
    year: -2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "hyundai.jpg",
    color: { short: "cyan", long: "light blue" },
    featured: false,
    details: {
      transmission: "automatic",
      seats: "4 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "jeep",
    brand: "Jeep",
    model: "Wrangler Rubicon",
    year: 2020,
    description:
      "The Jeep Wrangler is a series of compact and mid-size four-wheel drive off-road SUVs manufactured by Jeep since 1986, and currently in its fourth generation. The Wrangler JL, the most recent generation, was unveiled in late-2017 and is produced at Jeep's Toledo Complex.",
    image: "jeep.jpg",
    color: { short: "black", long: "black" },
    featured: false,
    details: {
      transmission: "automatic",
      seats: "2 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '17" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "bmw-m4-gts",
    brand: "BMW",
    model: "M4 GTS",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "bmw-white.jpg",
    color: { short: "white", long: "pearl white" },
    featured: false,
    details: {
      transmission: "automatic",
      seats: "4 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "ford-mustang-shelby-gt350r",
    brand: "Ford",
    model: "Mustang Shelby GT350R",
    year: 2020,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "mustang.jpg",
    color: { short: "black", long: "black matte" },
    featured: false,
    details: {
      transmission: "automatic",
      seats: "2 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "scooter",
    brand: "???",
    model: "Lorem ipsum",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "scooter.jpg",
    color: { short: "black", long: "pearl black" },
    featured: false,
    details: {
      transmission: "automatic",
      seats: "1 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "bianchi-c-sport",
    brand: "Bianchi",
    model: "C-Sport",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "bike.jpg",
    color: { short: "white", long: "pearl white" },
    featured: false,
    details: {
      transmission: "automatic",
      seats: "1 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
  {
    slug: "boat",
    brand: "???",
    model: "Lorem ipsum",
    year: 2018,
    description:
      "A standard car rental is a larger sedan, which provides more room for passengers and can fit an additional bag in the trunk compared to an intermediate car.",
    image: "boat.jpg",
    color: { short: "white", long: "pearl white" },
    featured: false,
    details: {
      transmission: "automatic",
      seats: "7 people",
      price: "300",
      bags: "3 bags",
      autonomy: "507 Km",
      capacity: "649 L",
    },
    features: [
      "Air Conditioning",
      "Cruise Control",
      "AM/FM Stereo Radio",
      "Bluetooth",
      "Electric",
      '15" digital screen',
      '20" wheels',
      "Autopilot",
    ],
  },
];
